// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:62bf3613-7a2c-4633-a189-879f16552c69",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_l5x5uwHRa",
    "aws_user_pools_web_client_id": "mmsg4bdggq6nhrsqa781gpknh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://55nxlui2xzg4jg5xcw4oy77z2e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
